kind: Service
apiVersion: v1
metadata:
  name: todo
  namespace: default
  uid: aa3ccfeb-85dc-4733-9e9a-3036f915e8b8
  resourceVersion: '3604'
  creationTimestamp: '2021-12-01T17:07:23Z'
  labels:
    k8s-app: todo
  managedFields:
    - manager: dashboard
      operation: Update
      apiVersion: v1
      time: '2021-12-01T17:07:23Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:k8s-app: {}
        f:spec:
          f:allocateLoadBalancerNodePorts: {}
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":5000,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
spec:
  ports:
    - name: tcp-5000-5000-vzpxl
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30323
  selector:
    k8s-app: todo
  clusterIP: 10.104.165.9
  clusterIPs:
    - 10.104.165.9
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
status:
  loadBalancer: {}
